--- 
title: "Audit Analytics Chapter Synopses (~50 words each)"
subtitle: "Chapters 1-13"
author: "J. Christopher Westland"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
  word_document: default
  html_document:
    theme: null
always_allow_html: yes
header-includes:
 \usepackage{float}
---



## Chapter 1:  Fundamentals of Auditing Financial Reports

Audits are independent examinations of the records of an organization to ascertain how far the financial statements present a true picture of the firm, and that accounting systems are well-controlled, legal and accurate. Auditing has become such a ubiquitous phenomenon in the world that academics have chronicled the transition to "Audit Societies".  The early $20^{th}$ century saw the standardization of auditors' tests and reporting. Statistical sampling and computer tools to conduct statistical samples and opinions based on them are an integral part of modern auditing. This chapter surveys the state of the profession and what the $21^{st}$ auditor needs to know.

## Chapter 2: Foundations of Audit Analytics

Broad application of statistical and data analytic tools are essential for the cost-effective completion of audits.  Fortunately R has become the go to language for analytics, and offers many features that reduce the cost of data acquisition, preparation, exploration and summarization.  It provides a scientific basis for audit decisions underlying the auditor's opinion.  Effective legal defense of audit methods is predicated on data analytics and statistical methods.  This chapter summarizes the subset of R capabilities that are germane to an audit.

## Chapter 3: Analysis of Accounting Transactions

Accounting transactions are the 'raw data' of accounting system, but the idiosyncratic vernacular of accounting, and spotty empirical study of distributions and characteristics of accounting transactions mean that statistical methods that are applied in other disciplines are likely to prove suboptimal, and even counterproductive in auditing.  This chapter delineates the idiosyncrasies of accounting transactions and summaries, and describes tools to cost-effectively prepare and render decisions from client accounting data. 

## Chapter 4: Risk Assessment and Planning

Risk assessment, planning and budgeting of audits are essential precursors to the successful audit.   The determination of risk of a particular subset of accounting operations related to the rendering of the audit opinion – i.e., on whether the accounts have material error when GAAP has been consistently applied.  This chapter delineates construction of the _risk assessment matrix_ – a collaborative “learning” worksheet to support a scientific foundation for audit scope, planning and budgeting prior to initiation of audit field tests. 

## Chapter 5: Analytical Review -- Technical Analysis

Analytical procedures are evaluations of financial information made by a study of plausible relationships between both financial and non-financial data. They are used in all stages of the audit including planning, substantive testing and final review stage. This chapter surveys a range of R packages that ease technical analysis and data collection tasks in analytical review.


## Chapter 6: Analytical Review -- Intelligence Scanning

Before the mid-2000s, inexpensive access to financial and non-financial data was spotty, unreliable and scarce. Today, there are numerous social network, news and discussion boards that offer both raw and curated, streaming sources of useful business intelligence available that allow analytical procedures to study the plausible relationships between both financial and non-financial data. The auditor who does not scan for such client and industry intelligence both increases the cost of auditing, and can be considered negligent in not investigating all available information about the financial health of their client.  


## Chapter 7: Design of Audit Programs

Audit programs, from a scientific perspective, _natural experiments_ -- they are empirical studies in which the activities of firms, individuals or groups are exposed to the experimental and control conditions that are determined by nature or by other factors outside the control of the auditors.  This chapter details the cost-effective planning for an audit, based on a deep understanding of natural experiments and the proper analytical tools needed to draw conclusions from them.  


## Chapter 8: Interim compliance tests

Compliance tests determine whether the firm’s transaction processing is in compliance with generally accepted accounting principles (GAAP).   They have grown increasingly important and are the basis for much of the reporting in the SAS No. 115 letter to management, and support management’s response in the Sarbanes-Oxley letter.  This chapter delineates the statistical tools used to insure cost effective compliance testing in the audit.


## Chapter 9: Substantive Tests

Substantive testing directly supports the auditor's opinion that economic events in the real world are or are not accurately summarized in the financial statements of a firm. This chapter delineates the statistical tools used to insure cost effective substantive testing in the audit.

## Chapter 10: Sarbanes-Oxley Engagements

Academic research on reporting from Sarbanes-Oxley Act of 2002 (SOX) has to date focused on internal consistency, compliance and accrual accounting assessments.  Some research has been performed on the related external risks such as fraud and security breaches.  This chapter surveys what we know about compliance cost and information content of SOX filings, and provides machine learning tools to assess the information contained in SOX reports. 

## Chapter 11: Blockchains, Cybercrime and Forensics

Auditors are often asked to opine on technical security and encryption technologies, as well as providing admissible evidence in legal cases.  This chapter reviews the most commonly encountered security and encryption technologies, with guides to how auditors should assess and manage them.

## Chapter 12: Special Engagements: Forecasts and Valuation

Auditors have an intimate understanding of their client’s finances.  Because of that, they are likely to be called upon to assess the value of a new or existing investment.  This chapter reviews the factors that go into performing a successful assurance and valuation assessment for a client. 


## Chapter 13: Simulated Transactions for Auditing Service Organizations

Testing the shared, proprietary $3^{rd}$-party platforms of service organizations and cloud computing presents auditors with a significant challenge. Auditors in these reviews can test automated controls by reading a 'deck' of known transactions and comparing these with the accounting reports generated by a client's automated system. This chapter delineates procedures for constructing and using these methods.
